buildscript {
    repositories {
        maven { url 'https://mirrors.cloud.tencent.com/gradle/' }
        maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
        mavenCentral()
        google()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.13.2"
    }
}

allprojects {
    repositories {
        maven { url 'https://mirrors.cloud.tencent.com/gradle/' }
        maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}
